package GUI;

import BL.Diagnosis;
import BL.Doctor;
import BL.Drug;
import BL.FullAppointment;
import BL.Hospital;
import BL.Patient;
import BL.Test;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DoctorModule extends javax.swing.JFrame {

    private Hospital hospitalManager;
    private Doctor loggedDoctor;
    private Patient currentPatient;
    private DefaultListModel listModelPatients;
    
    public DoctorModule() {
        super("Doctor module");
        initComponents();
        this.setVisible(true);
        logoutBtn.setVisible(false);
        selectPanel.setVisible(false);
        hospitalManager = new Hospital();
        listModelPatients = new DefaultListModel();
        this.appointmentManagerPanel2.setManager(hospitalManager);
        this.appointmentManagerPanel2.setVisible(false);

        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        yourIDLbl = new javax.swing.JLabel();
        loginTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        loginInfoLbl = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        selectPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientSearchList = new javax.swing.JList<>();
        selectBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        patientSearchTxt = new javax.swing.JTextField();
        setAppointmentBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        appointmentManagerPanel2 = new GUI.AppointmentManagerPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        yourIDLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yourIDLbl.setText("Your ID:");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loginInfoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(yourIDLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourIDLbl)
                    .addComponent(loginTxt)
                    .addComponent(loginBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginInfoLbl)
                    .addComponent(logoutBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        selectPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        patientSearchList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        patientSearchList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                patientSearchListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(patientSearchList);

        selectBtn.setText("Select");
        selectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        patientSearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientSearchTxtActionPerformed(evt);
            }
        });

        setAppointmentBtn.setText("Set appointment");
        setAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setAppointmentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectPanelLayout = new javax.swing.GroupLayout(selectPanel);
        selectPanel.setLayout(selectPanelLayout);
        selectPanelLayout.setHorizontalGroup(
            selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectPanelLayout.createSequentialGroup()
                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(selectPanelLayout.createSequentialGroup()
                            .addComponent(patientSearchTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchBtn)))
                    .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(selectBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setAppointmentBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        selectPanelLayout.setVerticalGroup(
            selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectPanelLayout.createSequentialGroup()
                .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(setAppointmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentManagerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(appointmentManagerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 290, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientSearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientSearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientSearchTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String search = patientSearchTxt.getText();

        try {
            if(search!=null){
                if(search.trim().length()!= 0){

                    //CLEAR DATA
                    //listModelPaidBills.clear();
                    //listModelUnpaidBills.clear();
                    //currentBill = null;

                    ArrayList<Patient> searchPatients = hospitalManager.searchPatientByName(search);
                    listModelPatients.clear();

                    for (Patient patient : searchPatients) {
                        listModelPatients.addElement(patient);
                    }
                    patientSearchList.setModel(listModelPatients);
                    patientSearchList.setSelectedIndex(0);
                }
            }

        } catch (SQLException ex) {
            new DBErrorDialog();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void selectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBtnActionPerformed
        if (!patientSearchList.isSelectionEmpty()) {
            currentPatient = (Patient)listModelPatients.getElementAt(patientSearchList.getSelectedIndex());
            
            //SAVE
            appointmentManagerPanel2.clearAll();
            
            appointmentManagerPanel2.setVisible(true);
            appointmentManagerPanel2.setAppointment(loggedDoctor, currentPatient);
        }
        else{
            appointmentManagerPanel2.setVisible(false);
            appointmentManagerPanel2.clearAppointmentData();
        }
    }//GEN-LAST:event_selectBtnActionPerformed

    private void patientSearchListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_patientSearchListValueChanged
        if (!patientSearchList.isSelectionEmpty()) {
            currentPatient = (Patient)listModelPatients.getElementAt(patientSearchList.getSelectedIndex()); //Logger.getLogger(PaymentPanel.class.getName()).log(Level.SEVERE, null, ex);
            //selectedPatientLbl.setText("SELECTED: " + currentPatient.toString());
        }
    }//GEN-LAST:event_patientSearchListValueChanged

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        currentPatient = null;
        loggedDoctor = null;
        selectPanel.setVisible(false);
        loginInfoLbl.setText("");
        loginBtn.setVisible(true);
        loginTxt.setVisible(true);
        yourIDLbl.setVisible(true);
        logoutBtn.setVisible(false);
        loginTxt.setText("");
        patientSearchTxt.setText("");
        listModelPatients.clear();
        appointmentManagerPanel2.setVisible(false);
        appointmentManagerPanel2.clearAppointmentData();
        
       // this.appointmentManagerPanel2.setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String search = loginTxt.getText();
        int doctorID;
        try {
            if(search!=null){
                if(search.trim().length()!= 0){
                    try {
                        doctorID = Integer.parseInt(search);
                    }
                    catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Please enter valid number");
                        return;
                    }

                    if (!hospitalManager.doctorExists(doctorID)) {
                        JOptionPane.showMessageDialog(null, "Doctor with such ID does not exist");
                        return;
                    }
                    loggedDoctor = hospitalManager.getDoctor(doctorID);
                    loginInfoLbl.setText("User: " + loggedDoctor);
                    loginBtn.setVisible(false);
                    loginTxt.setVisible(false);
                    yourIDLbl.setVisible(false);
                    logoutBtn.setVisible(true);
                    selectPanel.setVisible(true);
                }
            }

        } catch (SQLException ex) {
            new DBErrorDialog();
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void setAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setAppointmentBtnActionPerformed
        JFrame frame = new JFrame("Appointment creator");
        frame.add(new AppointmentsPanel(hospitalManager));
        frame.setSize(500,300);
        frame.setVisible(true);
    }//GEN-LAST:event_setAppointmentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.AppointmentManagerPanel appointmentManagerPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginInfoLbl;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JList<String> patientSearchList;
    private javax.swing.JTextField patientSearchTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton selectBtn;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JButton setAppointmentBtn;
    private javax.swing.JLabel yourIDLbl;
    // End of variables declaration//GEN-END:variables


}
